In [1]:
random =[i for i in range(0,10)]
random_map = list(map(lambda x : x-3 ,random))
print(random_map)

[-3, -2, -1, 0, 1, 2, 3, 4, 5, 6]


In [4]:
num = (range(0,20))
even_num = list(filter(lambda x: x%2==0,num))
print(even_num)



[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [32]:
num = (range(0,35))
odd_num = list(filter(lambda x: x%2!=0,num))
print(odd_num)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33]


In [10]:
numbers =( i for i in range(0,30))
random_numbers= list(map(lambda x: x+2,numbers))
print(random_numbers)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]


In [6]:
random =[chr(i)for i in range(65,91)]

In [7]:
random_map = list(map(lambda x : x + "E",random ))

In [8]:
random_map

['AE',
 'BE',
 'CE',
 'DE',
 'EE',
 'FE',
 'GE',
 'HE',
 'IE',
 'JE',
 'KE',
 'LE',
 'ME',
 'NE',
 'OE',
 'PE',
 'QE',
 'RE',
 'SE',
 'TE',
 'UE',
 'VE',
 'WE',
 'XE',
 'YE',
 'ZE']

In [9]:
random =[i for i in range(0,10)]
random_map = list(map(lambda x : x-3 ,random))
print(random_map)

[-3, -2, -1, 0, 1, 2, 3, 4, 5, 6]


In [97]:
random =[i for i in range(0,10)]
random_map = list(map(lambda x : x-5 ,random))
print(random_map)


[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]


In [13]:
random = [chr(i) for i in range(65,91)]


In [ ]:
random_map = list(map(lambda x : x + "E",random ))


In [16]:
random_map

['AE',
 'BE',
 'CE',
 'DE',
 'EE',
 'FE',
 'GE',
 'HE',
 'IE',
 'JE',
 'KE',
 'LE',
 'ME',
 'NE',
 'OE',
 'PE',
 'QE',
 'RE',
 'SE',
 'TE',
 'UE',
 'VE',
 'WE',
 'XE',
 'YE',
 'ZE']

In [18]:
random =(range(0,30))
random_map = list(map(lambda x:x+10,random))
print(random_map)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]


In [27]:
random =(range(0,120))
random_map = list(map(lambda x,:x+x,random))
print(random_map)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238]


In [36]:
num1=(range(0,50))
num2=(range(0,50))
check_list=list(map(lambda x,y:x+y,num1,num2))
print(check_list)



[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [37]:
numbers = (range(1,10))
squared = list(map(lambda num: num ** 2, numbers))

print(squared)

[1, 4, 9, 16, 25, 36, 49, 64, 81]


In [38]:
import functools
numbers =(range(0,12))
print(functools.reduce(lambda a,b: a+b,numbers))



66


In [59]:
def function():
    num = range(0,52)
    even_num =list(filter(lambda x:x%2==0,num))
print(even_num)
function()
    

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [60]:
def function():
    num = (range(1,20))
    odd_num = list(filter(lambda x: x%2!=0,num))
print(odd_num)
function()


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33]


In [66]:
# def function():
#     num = (range(0,30))
#     random=list(map(lambda x:x+5,num))
# print(random) 
# function()
    
    

range(0, 120)


In [74]:
random = [chr(i) for i in range(65,91)]
random = list(map(lambda x: x+"H",random))
print(random)


['AH', 'BH', 'CH', 'DH', 'EH', 'FH', 'GH', 'HH', 'IH', 'JH', 'KH', 'LH', 'MH', 'NH', 'OH', 'PH', 'QH', 'RH', 'SH', 'TH', 'UH', 'VH', 'WH', 'XH', 'YH', 'ZH']


In [80]:
random = [chr(i)for i in range(65,91)]
random_map  = list(map(lambda x: x+"j",random))
print(random_map) 


['Aj', 'Bj', 'Cj', 'Dj', 'Ej', 'Fj', 'Gj', 'Hj', 'Ij', 'Jj', 'Kj', 'Lj', 'Mj', 'Nj', 'Oj', 'Pj', 'Qj', 'Rj', 'Sj', 'Tj', 'Uj', 'Vj', 'Wj', 'Xj', 'Yj', 'Zj']


In [82]:
def function():
    random = [chr(i)for i in range(65,91)]
random_map  = list(map(lambda x: x+"k",random))
print(random_map)
function()



['Ak', 'Bk', 'Ck', 'Dk', 'Ek', 'Fk', 'Gk', 'Hk', 'Ik', 'Jk', 'Kk', 'Lk', 'Mk', 'Nk', 'Ok', 'Pk', 'Qk', 'Rk', 'Sk', 'Tk', 'Uk', 'Vk', 'Wk', 'Xk', 'Yk', 'Zk']


In [84]:
def fucntion():
    name =range(65,91)
random_name =list(map(lambda x: x+"M",random)) 
print(random_name)
fucntion()
    
    

['AM', 'BM', 'CM', 'DM', 'EM', 'FM', 'GM', 'HM', 'IM', 'JM', 'KM', 'LM', 'MM', 'NM', 'OM', 'PM', 'QM', 'RM', 'SM', 'TM', 'UM', 'VM', 'WM', 'XM', 'YM', 'ZM']


In [85]:
alphabets=[chr(i) for i in range(65,91)]
vowels = list(filter(lambda x: x in ["A","E","I","O","U"],alphabets))
consonent = list(filter(lambda x: x not in ["A","E","I","O","U"],alphabets))

In [86]:
print(vowels)


['A', 'E', 'I', 'O', 'U']


In [87]:
print(consonent)

['B', 'C', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z']


In [89]:
def function():
  alphabets=[chr(i) for i in range(65,91)]
vowels = list(filter(lambda x: x in ["A","E","I","O","U"],alphabets))
consonent = list(filter(lambda x: x not in ["A","E","I","O","U"],alphabets))
print(vowels,consonent)
function()


['A', 'E', 'I', 'O', 'U'] ['B', 'C', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z']


In [92]:
import functools
numbers =(range(0,130))
print(functools.reduce(lambda a,b: a+b,numbers))



8385


In [93]:
import functools
numbers =(range(0,12))
print(functools.reduce(lambda a,b: a+b,numbers))



66


In [10]:
import functools
numbers =(range(0,15))
print(functools.reduce(lambda a,b: a/b,numbers))

0.0


In [ ]:
import functools
numbers =(range(0,15))
print(functools.reduce(lambda a,b: a+b,numbers))

In [96]:
import functools
numbers =(range(1,10))
print(functools.reduce(lambda a,b:a*b,numbers ))

362880


In [3]:
num1 =(range(1,35))
num2 =(range(2,20))
random_num =list(map(lambda x,y:x*y,num1,num2)) 
print(random_num)

[2, 6, 12, 20, 30, 42, 56, 72, 90, 110, 132, 156, 182, 210, 240, 272, 306, 342]


In [19]:
from functools import reduce

list = [2, 4, 7, 3]
print(reduce(lambda x, y: x + y, list))
print("With an initial value: " + str(reduce(lambda x, y: x + y, list,10)))

16
With an initial value: 26


In [22]:
def add(x, y):
    return x + y

list = [2, 4, 7, 3]
print(reduce(add, list))

16


In [50]:
import functools 
def range(num):
    num =(range(1,10))
    return x + y
print(functools.reduce(lambda x,y :x+y,num))






595


In [58]:
import functools
def range(num):
        num =(range(1,5))
print(functools.reduce(lambda x,y:x*y,num))






295232799039604140847618609643520000000


TypeError: function() takes 0 positional arguments but 1 was given

In [62]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  pass

x = Student("Mike", "Olsen")
x.printname()


Mike Olsen


In [3]:
class person:
 def __init__(self,name):
    self.name=name
 def printname(self):
    print(self.name)
x= person('bhawana')
x.printname()

bhawana


In [2]:
class person:
    def __init__(self,fname,lname):
        self.firstname =fname
        self.lastname =lname
    def printname(self):
        print(self.firstname,self.lastname)
class student(person):
    pass
x= student("bhawana","shinde")
x.printname()
        

bhawana shinde


In [106]:
class person: 
  def __init__(self, fname, lname):
    self.firtsname = fname
    self.lastname = lname
    
  def printname(self):
         print(self.firstname,self.lastname)
        
class student(person):
   pass

x = Student("Mike","olsen")
x.printname()


Mike olsen


In [5]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
        print(self.firstname, self.lastname)
x = person("Mike", "Olsen")
x.printname()


Mike Olsen


In [101]:
def myfun():
    for i in range(1,10):
        if i<=10:
            print(i)
            
        else:
            print("lll")
myfun()       
       



TypeError: range() takes 1 positional argument but 2 were given

In [6]:
num =(range(1,20))
even_num =list(filter(lambda x: x%2==0,num))
print(even_num)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [8]:
numbers = (range(0,30))
random_numbers= list(map(lambda x: x+1,numbers))
print(random_numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [16]:
alphabets=[chr(i) for i in range(65,91)]
vowels = list(filter(lambda x: x in ["A","E","I","O","U"],alphabets))
consonent = list(filter(lambda x: x not in ["A","E","I","O","U"],alphabets))

In [14]:
alphabets =[chr(i) for i in range(65,91)]
vowels = list(map(lambda x: x in ["A","E","I","O","U"],alphabests))
consonent = list(filter(lambda x: x not in["A","E","I","O","U"],alphabets))

In [17]:
print(vowels)


['A', 'E', 'I', 'O', 'U']


In [18]:
print(consonent)

['B', 'C', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z']


In [23]:
import re

name = "My name is bhawana"
A =  re.search("", name)
if name:
  print("YES! We have a match!")
else:
  print("No match")



YES! We have a match!


In [24]:
price=50
txt = "The price is {:.2f} dollars"

In [26]:
print(txt.format(price))

The price is 50.00 dollars


In [31]:
print("bhawana")

bhawana


In [19]:
f = open('C:/flower.jpg','rb')
print(f.read())


b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00\x84\x00\n\x07\x08\x15\x15\x15\x18\x15\x16\x15\x18\x18\x18\x18\x19\x18\x18\x18\x15\x19\x18\x18\x18\x18\x19\x18\x18\x18\x19\x19\x18\x18\x18\x1a\x1c!.%\x1c\x1e+\x1f\x18\x18&8&+/1555\x1a$;@;4?.451\x01\x0c\x0c\x0c\x10\x0f\x10\x1a\x12\x12\x1e4+!$44444444444144444444444444454444444444444444444414\xff\xc0\x00\x11\x08\x00\xb7\x01\x13\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1b\x00\x00\x02\x02\x03\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x04\x02\x05\x00\x01\x06\x07\xff\xc4\x00;\x10\x00\x02\x01\x02\x03\x05\x06\x04\x06\x00\x05\x05\x01\x00\x00\x00\x01\x02\x00\x03\x11\x04!1\x05\x12AQa\x06"q\x81\x91\xb1\x13\xa1\xc1\xd1\x142BR\xe1\xf0$br\xa2\xf1\x07#C\x92\xc2\x15\xff\xc4\x00\x19\x01\x00\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\xff\xc4\x00&\x11\x00\x03\x01\x00\x02\x02\x02\x02\x01\x05\x01\x00\x00\x00\x00\x00\x00\x01\x02\x11\x03!\x121\x04A"Q\x13\x14aq\x81\x912\

In [20]:
f = open("C:/flower.jpg",'rb')
print(f.read())

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00\x84\x00\n\x07\x08\x15\x15\x15\x18\x15\x16\x15\x18\x18\x18\x18\x19\x18\x18\x18\x15\x19\x18\x18\x18\x18\x19\x18\x18\x18\x19\x19\x18\x18\x18\x1a\x1c!.%\x1c\x1e+\x1f\x18\x18&8&+/1555\x1a$;@;4?.451\x01\x0c\x0c\x0c\x10\x0f\x10\x1a\x12\x12\x1e4+!$44444444444144444444444444454444444444444444444414\xff\xc0\x00\x11\x08\x00\xb7\x01\x13\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1b\x00\x00\x02\x02\x03\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x04\x02\x05\x00\x01\x06\x07\xff\xc4\x00;\x10\x00\x02\x01\x02\x03\x05\x06\x04\x06\x00\x05\x05\x01\x00\x00\x00\x01\x02\x00\x03\x11\x04!1\x05\x12AQa\x06"q\x81\x91\xb1\x13\xa1\xc1\xd1\x142BR\xe1\xf0$br\xa2\xf1\x07#C\x92\xc2\x15\xff\xc4\x00\x19\x01\x00\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\xff\xc4\x00&\x11\x00\x03\x01\x00\x02\x02\x02\x02\x01\x05\x01\x00\x00\x00\x00\x00\x00\x01\x02\x11\x03!\x121\x04A"Q\x13\x14aq\x81\x912\

In [31]:
f = open('C:/flower.jpg', 'rt')
print(f)

<_io.TextIOWrapper name='C:/flower.jpg' mode='rt' encoding='cp1252'>


In [147]:
f = open('C:/flower.jpg','r')
print(f)


<_io.TextIOWrapper name='C:/flower.jpg' mode='r' encoding='cp1252'>


In [78]:
f = open('C:/flower.jpg', 'w')
print(f)

PermissionError: [Errno 13] Permission denied: 'C:/flower.jpg'

In [77]:
f = open('C:/flower.jpg', 'rt')
print(f)

<_io.TextIOWrapper name='C:/flower.jpg' mode='rt' encoding='cp1252'>


In [80]:
myfile.txt  = 'my name is vaishali'

In [107]:
f = open('myfile.txt','r')
print(f)

<_io.TextIOWrapper name='myfile.txt' mode='r' encoding='cp1252'>


In [123]:
h = open('abc.txt',"r")
print(h.read())

In [88]:
f = open("C:/flower.jpg",'rb')

lines = f.readlines()

for line in lines:

    print(line.rstrip())

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00\x84\x00'
b'\x07\x08\x15\x15\x15\x18\x15\x16\x15\x18\x18\x18\x18\x19\x18\x18\x18\x15\x19\x18\x18\x18\x18\x19\x18\x18\x18\x19\x19\x18\x18\x18\x1a\x1c!.%\x1c\x1e+\x1f\x18\x18&8&+/1555\x1a$;@;4?.451\x01\x0c\x0c\x0c\x10\x0f\x10\x1a\x12\x12\x1e4+!$44444444444144444444444444454444444444444444444414\xff\xc0\x00\x11\x08\x00\xb7\x01\x13\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1b\x00\x00\x02\x02\x03\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x04\x02\x05\x00\x01\x06\x07\xff\xc4\x00;\x10\x00\x02\x01\x02\x03\x05\x06\x04\x06\x00\x05\x05\x01\x00\x00\x00\x01\x02\x00\x03\x11\x04!1\x05\x12AQa\x06"q\x81\x91\xb1\x13\xa1\xc1\xd1\x142BR\xe1\xf0$br\xa2\xf1\x07#C\x92\xc2\x15\xff\xc4\x00\x19\x01\x00\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\xff\xc4\x00&\x11\x00\x03\x01\x00\x02\x02\x02\x02\x01\x05\x01\x00\x00\x00\x00\x00\x00\x01\x02\x11\x03!\x121\x04A"Q\x13\x14aq\x81\x91

In [15]:
with open("C:/flower11.jpg","rb") as f:
    with open("F:/flower11_new.jpg", 'wb') as file:
        file.write(f.read())

In [17]:
with open ("C:/flower11.jpg","rb") as f:
    with open("F:/flower11_new.jpg", 'wb') as file:
        file.write(f.read())
        


In [14]:
f = open("C:/flower.jpg",'r')
print(f)



<_io.TextIOWrapper name='C:/flower.jpg' mode='r' encoding='cp1252'>


In [145]:
f = open("demofile2.txt", "a")
f.write("Now the file has more content!")
f.close()

#open and read the file after the appending:
f = open("demofile2.txt", "r")
print(f.read())

Now the file has more content!Now the file has more content!Now the file has more content!Now the file has more content!Now the file has more content!


In [164]:
quantity = 3
itemno = 567
price = 49
myorder = "I want {} pieces of item number {} for {:.2f} dollars."
print(myorder.format(quantity, itemno, price))


I want 3 pieces of item number 567 for 49.00 dollars.


In [125]:
price = 49
txt = "The price is {} dollars"
print(txt.format(price))

The price is 49 dollars


In [128]:
price =50
txt = "item quantity is 50"
print(txt.format(price))

item quantity is 50


In [130]:
price = 49
txt = "The price is{} dollars"
print(txt.format(price))

The price is49 dollars


In [132]:
txt = "The price is {:.2f} dollars"
print(txt.format(price))

The price is 49.00 dollars


In [14]:
f = open("C:/flower.jpg",'rb')
print(f)

<_io.BufferedReader name='C:/flower.jpg'>


In [277]:
f = open ("C:/xyz.txt","r")
print(f.read())

my name is bhawana.
its my class.


In [279]:
f = open("C:/xyz.txt","rb")
print(f.read())


b'my name is bhawana.\r\nits my class.'


In [244]:
f = open("C:/Users/LENOVO/abcc.txt","r")
print(f.read())

HELLO WORLD in f.


In [208]:
f = open("C:/Users/LENOVO/abcc.txt",'rb')
print(f.read())


b'HELLO WORLD in f.'


In [22]:
f = open("C:/Users/LENOVO/abcc.txt","w")
f.write("HELLO WORLD in f.")
f.close()


       

In [259]:
f = open("C:/world1.text","r")
print(f.read())




FileNotFoundError: [Errno 2] No such file or directory: 'C:/world1.text'

In [229]:
f = open("C:/Users/LENOVO/abcc.txt","rb")
print(f.read())


b'HELLO WORLD in f.'


In [210]:
f = open("C:/Users/LENOVO/abcc.txt", "r")
for x in f:
  print(x)


HELLO WORLD in f.


In [68]:
f =open("C:/Users/LENOVO/abcc.txt",mode="r")
number_of_words=0
number_of_chars=0
number_of_lines=0
for line in f:
    number_of_lines+=1
    line=line.strip("\n")
    number_of_chars += len(line)
    
    list1=line.split()
    number_of_words += len(list1)
f.close()    

In [11]:
f = open("C:/Users/LENOVO/abcc.txt","w")
f.write("Hello! Welcome to demofile.txt")
f.close()


# check image in the save drive

In [67]:
with open("C:/flower.jpg","rb") as f:
    with open("F:/flower_new.jpg", 'wb') as file:
        file.write(f.read())

In [70]:
c1 = Customer("95774238923")

In [71]:
c1.get_number()

95774238923


In [11]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
        print(self.firstname, self.lastname)
x = person("Mike", "Olsen")
x.printname()

Mike Olsen


In [7]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname):
    super().__init__(fname, lname)

x = Student("Mike", "Olsen")
x.printname()



Mike Olsen


In [75]:
with open("F:/tree.jpg" ,"rb") as f:
          with open("F:/tree.jpg","wb") as file:
            file.write(f.read())

In [105]:
with open("C:/butterf.jpg","rb") as f:
    with open("F:/butterfa.jpg","wb") as file:
        file.write(f.read())

In [108]:
with open("C:/butterf.jpg","rb") as f:
    with open("F:/butterfbb.jpg","wb") as file:
        file.write(f.read())

In [87]:
f = open("C:/Users/LENOVO/abcc.txt","r")
print(f.readline())
f.close()

HELLO WORLD in f.


In [96]:
class customer:
    def __init__(self,filename,officename):
        self.filename = filename
        self.officename = officename
    def printname(self):
        print(self.filename,self.officename)
x = customer("craft", "javapoint")
x.printname()    

craft javapoint


In [ ]:
 def printname(self):
    print(self.firstname, self.lastname)

#Use the Person class to create an object, and then execute the printname method:

x = Person("John", "Doe")
x.printname()

In [94]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

#Use the Person class to create an object, and then execute the printname method:

x = Person("John", "Doe")
x.printname()

John Doe


In [97]:
class Customer:
    def __init__(self,mob):
        self.number = mob
        
    def get_number(self):
        print(self.number)
c1 = Customer("95774238923")
c1.get_number()

95774238923


In [102]:
class section:
    def __init__(self,section,standard):
        self.section = section
        self.standard = standard
    def printname(self):
        print(self.section,self.standard)
x = section("A+","10th")
x.printname()

        

A+ 10th


In [113]:
 with open("C:/butterf.jpg","rb") as f:
    with open("F:/butterfa.jpg","wb") as file:
        file.write(f.read())

In [115]:
class section:
    def __init__(self, name,age):
        self.name = name
        self.age  = age
    def printname(self):
        print(self.name,self.age)
x= section("bhawana","28")
x.printname()

bhawana 28


In [120]:
class function:
    def __init__(self,subject,row):
        self.subject =subject
        self.row     = row
    def printname(self):
        print(self.subject,self.row)
x = function("englis","5th")
x.printname()

englis 5th


In [8]:
class function():
    def __init__(self,city,colony):
        self.city = city
        self.colony = colony
    def printname(self):
        print(self.city,self.colony)
x = function("indore","xyz")
x.printname()

        
        
        
        
        
        
        

indore xyz


In [ ]:
alphabets=[chr(i) for i in range(65,91)]
vowels = list(filter(lambda x: x in ["A","E","I","O","U"],alphabets))
consonent = list(filter(lambda x: x not in ["A","E","I","O","U"],alphabets))

In [4]:
alphabets=[chr(i)for i in range(65,91)]
vowels = list(filter(lambda x:x in["A","E","I","O","U"],alphabets ))
consonent = list(filter(lambda x: x not in["A","E","I","O","U"],alphabets))

In [5]:
print(vowels)

['A', 'E', 'I', 'O', 'U']


In [6]:
print(consonent)

['B', 'C', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z']


In [10]:
random =(range(0,30))
random_map = list(map(lambda x:x+10,random))
print(random_map)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]


In [11]:
random_num = (range(1,10))
random_map =list(map(lambda x:x+5,random))
print(random_map)

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]


In [13]:
num = (range(1,20))
even_num =list(filter(lambda x: x%2==0,random))
print(even_num)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]


In [40]:
class function():
    def __init__(self,city,colony):
        self.city = city
        self.colony = colony
    def printname(self):
        print(self.city,self.colony)
x = function("indore","xyz")
x.printname()


indore xyz


In [18]:
class section:
    def __init__(self,section,standard):
        self.section = section
        self.standard = standard
    def printname(self):
        print(self.section,self.standard)
x = section("A+","10th")
x.printname()

        

A+ 10th


In [22]:
class section():
 def __init__(self,section,standard):
        self.section= section
        self.standard= standard
 def printname(self):
        print(self.section,self.standard)
x = section('A++','first')
x.printname()
    

A++ first


In [23]:
class section():
    def __init__(self,standard,section):
        self.standard = standard
        self.section = section
    def printname(self):
        print(self.standard,self.section)
x= section('b++','second')
x.printname()
        

b++ second


In [26]:
class Details():
 def __init__(self,name,address):
        self.name = name
        self.address = address
 def printname(self):
     print(self.name,self.address)
x = Details('ayz','indore')
x.printname()
        

ayz indore


In [29]:
import  numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [30]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [34]:
import numpy as np
arr = np.array([1,2,3])
newarr = arr.view()
print(newarr)
print(arr)

[1 2 3]
[1 2 3]


In [ ]:
import numpy as np
arr = np.array([2,5,6,7])
y = arr.view()
arr[1] = 32
print(arr)
print(y)


In [37]:
import numpy as np
arr = np.array([4,5,6,7])
x = arr.view()
print(arr)
print(x)

[4 5 6 7]
[4 5 6 7]


In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

In [45]:
import pandas as pd
A =[22,24,3]
myarr = pd.Series(A)
print(myarr)


0    22
1    24
2     3
dtype: int64


In [49]:
import pandas as pd
A =[1,2,3]
myarr = pd.Series(A,index =['a1','a2','a3'])
print(myarr)

a1    1
a2    2
a3    3
dtype: int64


In [ ]:
class Details():
 def __init__(self,name,address):
        self.name = name
        self.address = address
 def printname(self):
     print(self.name,self.address)
x = Details('ayz','indore')
x.printname()
        

In [4]:
class function():
  def __init__(self,name):
        self.name = name
  def printname(self):
        print(self.name)
x = function('bhawana')
x.printname()
        

bhawana


In [1]:
f = open('C:\opq.txt','r')
print(f)

<_io.TextIOWrapper name='C:\\opq.txt' mode='r' encoding='cp1252'>


In [4]:
f = open('C:\opq.txt','r')
print(f.read())

its a as pen,
she is good girl,
he is good boy.


In [28]:
f = open(r'C:\Users\LENOVO\Downloads\opq.txt','w')
f.write('its a as pen,f.')
f.close()

In [23]:
f = open("C:\opq.txt","w")
f.write("she is good girl.txt")
f.close()


PermissionError: [Errno 13] Permission denied: 'C:\\opq.txt'