In [32]:
from numpy import random

x = random.randint(50)

print(x)

6


In [36]:
import random

print(random.randrange(1, 10))


5


In [35]:
from numpy import random
x = random.randint(120)
print(x)

75


In [3]:
from numpy import random
x = random.randint(120)
print(x)

117


In [5]:
from numpy import random
y = random.randint(150)
print(x)

117


In [7]:
from numpy import random
x = random.randint(130)
print(x)

102


In [23]:
from numpy import random
x= random.randint(100)
print(x)

42


# value

In [8]:
from numpy import random

x = random.rand()

print(x)

0.8676597517010552


# float

In [9]:
from numpy import random
y = random.rand()
print(y)

0.6287487478306385


# random array

In [11]:
from numpy import random

x=random.randint(100, size=(5))

print(x)


[ 8  4 22 77 84]


In [38]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)


[[62 27 76 89  4]
 [10 79 26 94 67]
 [68  2 93 45 77]]


In [40]:
from numpy import random
x = random.randint(100,size=(5,4))
print(x)

[[79 81 65 95]
 [ 8 15  3 85]
 [29 32 81 50]
 [44 18 96 47]
 [40  4 43 41]]


In [41]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.60391348 0.55305657 0.29167083 0.81886115 0.93230249]
 [0.07128366 0.98695256 0.71055934 0.17321269 0.51062917]
 [0.96659327 0.26889436 0.75122103 0.39098785 0.39174495]]


In [37]:
from numpy import random
x= random.randint(150,size=(6))
print(x)

[ 7 35 39 33 24 31]


In [12]:
from numpy import random
x = random.randint(100,size=(6))
print(x)

[13 79 71 96 80 32]


In [16]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)


7


In [17]:
from numpy import random
y = random.choice([5,1,2,2])
print(y)

2


In [ ]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

In [14]:
from numpy import random
x = random.choice([1,2,5,6],size=(100))
print(x)

[1 5 6 1 1 5 1 1 1 6 1 6 1 2 2 6 5 2 2 1 2 2 2 6 6 1 5 2 1 6 5 5 1 1 1 1 5
 5 1 1 2 6 1 1 5 5 5 1 2 6 2 5 1 1 6 2 5 5 5 1 5 6 2 1 5 2 1 5 1 1 5 5 6 5
 6 1 1 1 6 1 5 5 5 5 5 5 2 5 2 5 1 5 6 5 6 2 6 1 2 5]
